package:
  name: line_profiler
  version: "1.0"

source:
  fn: line_profiler-1.0.tar.gz
  url: https://pypi.python.org/packages/source/l/line_profiler/line_profiler-1.0.tar.gz
  md5: 2f8352acfedf83f701a564583db5e14d

build:
  binary_relocation: True

  entry_points:
    - kernprof=kernprof:main

  number: 0

requirements:
  build:
    - python
    - cython
    - distribute

  run:
    - python

test:
  imports:
    - line_profiler

  commands:
    - kernprof --help

about:
  home: https://github.com/rkern/line_profiler
  license:  BSD License
  summary: 'Line-by-line profiler.'