package:
  name: pywavelets
  version: "0.5.1"

source:
  fn: PyWavelets-0.5.1.tar.gz
  url: https://pypi.python.org/packages/af/a7/310108f76adc8d4d91a7b685bc37f62d5b3475f72b31f20730cfdee68534/PyWavelets-0.5.1.tar.gz
  md5: 7a0388f56dbbbea037c779bc3fd32c33

build:
  number: 0

requirements:
  build:
    - python
    - cython >=0.16
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  requires:
    - nose

  imports:
    - pywt

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  summary: PyWavelets is a free Open Source library for wavelet transforms in Python.