package:
  name: pywavelets
  version: "0.4.0"

source:
  fn: PyWavelets-0.4.0.tar.gz
  url: https://pypi.python.org/packages/32/fd/55705cae2cced82b4a017c77bb71d994d74c04dc76cbad9116459f151f19/PyWavelets-0.4.0.tar.gz
  md5: 5b41cd6bf4bd7645aee8eaae72816853

build:
  number: 0

requirements:
  build:
    - python
    - cython >=0.16
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  requires:
    - nose

  imports:
    - pywt

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  summary: PyWavelets is a free Open Source library for wavelet transforms in Python.