package:
  name: pywavelets
  version: "0.5.0"

source:
  fn: PyWavelets-0.5.0.tar.gz
  url: https://pypi.python.org/packages/e6/e7/cf124a5444cfc86592c7a5d85aedf3d73954395b58d1992f1b2b974bf3bc/PyWavelets-0.5.0.tar.gz
  md5: a1498dcb4ce78b0e7eeaf840db781805

build:
  number: 0

requirements:
  build:
    - python
    - cython >=0.16
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  requires:
    - nose

  imports:
    - pywt

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  summary: PyWavelets is a free Open Source library for wavelet transforms in Python.