package:
  name: pywavelets
  version: "0.5.2"

source:
  fn: PyWavelets-0.5.2.tar.gz
  url: https://pypi.python.org/packages/4b/df/3fff2a8b96ef7df6e4e8642fb7569c3717ae562dd76afe0f96525c0af784/PyWavelets-0.5.2.tar.gz
  md5: aedda732f064cf9395f03d37f1003d1a

build:
  number: 0

requirements:
  build:
    - python
    - cython >=0.16
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  requires:
    - nose

  imports:
    - pywt

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  summary: PyWavelets is a free Open Source library for wavelet transforms in Python.