package:
  name: mando
  version: "0.4"

source:
  fn: mando-0.4.tar.gz
  url: https://pypi.python.org/packages/source/m/mando/mando-0.4.tar.gz
  md5: 1d3fe2ab518830d8984218d7b01b4631

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - sphinx

  run:
    - python
    - sphinx

test:
  imports:
    - mando
    - mando.tests

about:
  home: https://mando.readthedocs.org/
  license: MIT License
  summary: 'Create Python CLI apps with little to no effort at all!'
