package:
  name: mando
  version: "0.3.3"

source:
  fn: mando-0.3.3.tar.gz
  url: https://pypi.python.org/packages/source/m/mando/mando-0.3.3.tar.gz
  md5: 4244d87684a3c49b888dc702589a7d5b

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - mando
    - mando.tests

about:
  home: https://mando.readthedocs.org/
  license: MIT License
  summary: 'Create Python CLI apps with little to no effort at all!'
