package:
  name: mando
  version: "0.3.2"

source:
  fn: mando-0.3.2.tar.gz
  url: https://pypi.python.org/packages/source/m/mando/mando-0.3.2.tar.gz
  md5: d1bff21b490351a78129a8bb97a358e5

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - mando
    - mando.tests

about:
  home: https://mando.readthedocs.org/
  license: MIT License
  summary: 'Create Python CLI apps with little to no effort at all!'
