package:
  name: memory_profiler
  version: "0.31"

source:
  fn: memory_profiler-0.31.tar.gz
  url: https://pypi.python.org/packages/source/m/memory_profiler/memory_profiler-0.31.tar.gz
  md5: ab10ff2485a4258cd39237a0bf4b0295

build:
  binary_relocation: True
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - memory_profiler

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: Simplified BSD
  summary: 'A module for monitoring memory usage of a python program'

