package:
  name: memory_profiler
  version: "0.45"

source:
  fn: memory_profiler-0.45.tar.gz
  url: https://pypi.python.org/packages/e9/16/135a03bb71126cb8f097bb2789fb0c46e297a801995f051318fdd49631e2/memory_profiler-0.45.tar.gz
  md5: ea76e5119071744655769fce566b27cf

build:
  binary_relocation: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - memory_profiler

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: Simplified BSD
  summary: 'A module for monitoring memory usage of a python program'
