package:
  name: memory_profiler
  version: "0.47"

source:
  fn: memory_profiler-0.47.tar.gz
  url: https://pypi.python.org/packages/bf/f0/15dc10cac0d8c56782e51d94855955664aa4f420eaa6291314bc3a0a52a3/memory_profiler-0.47.tar.gz
  md5: ed340aaaa0c7118f2a4c5b4edec6da1e

build:
  binary_relocation: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - memory_profiler

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: Simplified BSD
  summary: 'A module for monitoring memory usage of a python program'
