package:
  name: memory_profiler
  version: "0.32"

source:
  fn: memory_profiler-0.32.tar.gz
  url: https://pypi.python.org/packages/source/m/memory_profiler/memory_profiler-0.32.tar.gz
  md5: c65310467e05d8db4b10fa65534f3e5d

build:
  binary_relocation: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - memory_profiler

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: Simplified BSD
  summary: 'A module for monitoring memory usage of a python program'

