package:
  name: memory_profiler
  version: "0.41"

source:
  fn: memory_profiler-0.41.tar.gz
  url: https://pypi.python.org/packages/source/m/memory_profiler/memory_profiler-0.41.tar.gz
  md5: 8615aecbcc5cf1a761c819b9f4976cad

build:
  binary_relocation: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - memory_profiler

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: Simplified BSD
  summary: 'A module for monitoring memory usage of a python program'
