package:
  name: memory_profiler
  version: "0.43"

source:
  fn: memory_profiler-0.43.tar.gz
  url: https://pypi.python.org/packages/ac/71/cb4cdac45861d7497e3bd6500b49fccfe5a3f2e57ba69933cba74abfef37/memory_profiler-0.43.tar.gz
  md5: 7b6cf03cbee3ad7f366261831282651a

build:
  binary_relocation: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - memory_profiler

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: Simplified BSD
  summary: 'A module for monitoring memory usage of a python program'
