package:
  name: radon
  version: "1.1.1"

source:
  fn: radon-1.1.1.tar.gz
  url: https://pypi.python.org/packages/source/r/radon/radon-1.1.1.tar.gz
  md5: fde2e27dd97e390c94c6d4b04abad5c4

build:
  entry_points:
    - radon = radon:main

  number: 0

requirements:
  build:
    - python
    - distribute
    - mando
    - colorama

  run:
    - python
    - mando
    - colorama

test:
  imports:
    - radon

  commands:
    - radon --help

about:
  home: https://radon.readthedocs.org/
  license: MIT License
  summary: 'Code Metrics in Python'

