package:
  name: radon
  version: "1.3.0"

source:
  fn: radon-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/r/radon/radon-1.3.0.tar.gz
  md5: c85e93d17d629d8a0db94d61a254d974

build:
  entry_points:
    - radon = radon:main

  number: 0

requirements:
  build:
    - python
    - setuptools
    - mando
    - colorama

  run:
    - python
    - mando
    - colorama

test:
  imports:
    - radon

  commands:
    - radon --help

about:
  home: https://radon.readthedocs.org/
  license: MIT License
  summary: 'Code Metrics in Python'
