package:
  name: sphinxcontrib-napoleon
  version: "0.2.8"

source:
  fn: sphinxcontrib-napoleon-0.2.8.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-napoleon/sphinxcontrib-napoleon-0.2.8.tar.gz
  md5: 004abec2393a8743a150a9d64a85d517
  patches:
   # List any patch files here
    - setup_py_no_tests_package.patch

# build:
  #preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sphinx 1.2*

test:
  # Python imports
  imports:
    - sphinxcontrib.napoleon

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD License
  summary: 'Sphinx "napoleon" extension.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
