package:
  name: sphinxcontrib-napoleon
  version: "0.3.1"

source:
  fn: sphinxcontrib-napoleon-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-napoleon/sphinxcontrib-napoleon-0.3.1.tar.gz
  md5: 8ac869008f9d687fb58d9e48ccded594
  patches:
    - setup_py_no_tests_package.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.7
    - pockets >=0.2.1
    - sphinx 1.2*

test:
  imports:
    - sphinxcontrib.napoleon

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD License
  summary: 'Sphinx "napoleon" extension.'
