package:
  name: sphinxcontrib-napoleon
  version: "0.4.3"

source:
  fn: sphinxcontrib-napoleon-0.4.3.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-napoleon/sphinxcontrib-napoleon-0.4.3.tar.gz
  md5: 088b3cbe63519497b5546c9f36b292db
  patches:
    - setup_py_no_tests_package.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.7
    - pockets >=0.2.1
    - sphinx 1.2*

test:
  imports:
    - sphinxcontrib.napoleon

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD License
  summary: 'Sphinx "napoleon" extension.'
