package:
  name: bottleneck
  version: "0.8.0"

source:
  fn: Bottleneck-0.8.0.tar.gz
  url: https://pypi.python.org/packages/source/B/Bottleneck/Bottleneck-0.8.0.tar.gz
  md5: 1a363fa35ce521eebb838e1bd6520e24

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8

  run:
    - python
    - numpy >=1.8

test:
  imports:
    - bottleneck

about:
  home: http://berkeleyanalytics.com/bottleneck
  license: BSD License
  summary: Fast NumPy array functions written in Cython
