package:
  name: bottleneck
  version: "1.0.0"

source:
  fn: Bottleneck-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/B/Bottleneck/Bottleneck-1.0.0.tar.gz
  md5: 380fa6f275bd24f27e7cf0e0d752f5d2

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9.1

  run:
    - python
    - numpy >=1.9.1

test:
  imports:
    - bottleneck

about:
  home: http://berkeleyanalytics.com/bottleneck
  license: BSD License
  summary: Fast NumPy array functions written in Cython
