package:
  name: pockets
  version: "0.2.4"

source:
  fn: pockets-0.2.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pockets/pockets-0.2.4.tar.gz
  md5: 92eff6116937edfed56a8ed44bb3b99b
  patches:
    - setup_py_no_tests_package.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six >=1.5.2

  run:
    - python
    - six >=1.5.2

test:
  imports:
    - pockets

about:
  home: http://pockets.readthedocs.org
  license: BSD License
  summary: 'A collection of helpful Python tools!'
